@startuml
'https://plantuml.com/class-diagram

class InventoryTracker {
    start()
    main()
}

class MainWindowController {
    items: ItemModel
    scenes: SceneManager
    fileManager: FileManager
    + MainWindowController(ItemModel, SceneManager)
    + addItem(String, String, BigDecimal)
    + addItemButtonClicked(EventHandler)
    + editItemButtonClicked(EventHandler)
    + removeItemButtonClicked(EventHandler)

}

class InventoryTrackerMethods {
    +addItem()
    +deleteItem()
    +edit()
    +search()
    +


}


class FileManager {
    saveInventoryasCSV(filename: Strin, data: String)
    saveInventoryasHTML(filename: String, data: String)
    saveInventoryasJSON(filename: String, data: String)
   }



class ItemModel {
    - ObservableList<Item>
}

class Item {
    - name: String
    - serialNumber: String
    - value: String

    +getName()
    +setName()
    +getSerialNumber()
    +setSerialNumber()
    +getValue()
    +setValue()
}

class SimpleItem {
    - name: SimpleStringProperty
    - serialNumber: SimpleStringProperty
    - value: SimpleDoubleProperty

    +getName()
    +setName()
    +getSerialNumber()
    +setSerialNumber()
    +getValue()
    +setValue()
}

InventoryTracker -- SceneManager
javafx.Application <|-- InventoryTracker

MainWindowController o-- ItemModel

MainWindowController o-- FileManager
ItemModel *-- Item
@enduml