@startuml
'https://plantuml.com/class-diagram

class App {
    start()
    main()
}

class ErrorMessage {
    showErrorAlert()
}

class InventoryTracker {
    + initialize()
    + changeNameCellEvent()
    + changePriceCellEvent()
    + changeSerialCellEvent()
    + deleteSelectedClicked()
    + addNewClicked()
    + saveTSV()
    + saveHTML()
    + saveJSON()
    + loadTSV()
    + loadHTML()
    +loadJSON()
}

class InventoryTrackerMethods {
    - inventory : ObservableList
    - SimpleItem
    + checkPrice()
    + checkName()
    + checkSerialUnique()
    + checkSerialFormatting()
    + addItem()
    + deleteItem()
    + searchItem()
    + tsvFormat()
    + tsvReader()
    + HTMLFormat()
    + readHTML()
    + serializeInventory()
    + deserialize()
    + saveTextToFile()
}

class InventoryTrackerTestMethods {
    - inventory : ArrayList
    - Item
}

class Item {
    - name: String
    - serialNumber: String
    - value: String

    + getName()
    + setName()
    + getSerialNumber()
    + setSerialNumber()
    + getValue()
    + setValue()
}

class SimpleItem {
    - name: SimpleStringProperty
    - serialNumber: SimpleStringProperty
    - value: SimpleDoubleProperty

    + getName()
    + setName()
    + getSerialNumber()
    + setSerialNumber()
    + getValue()
    + setValue()
}

javafx.Application <|-- App
SimpleItem <|- InventoryTrackerMethods
InventoryTrackerMethods <|-- InventoryTracker
Item <|-- InventoryTrackerTestMethods
InventoryTracker <|- javafx.Application
@enduml